CREATE TABLE VAERSData (
	VAERS_ID VARCHAR(6),
	RECVDATE DATE,
	STATE VARCHAR(2),
	AGE_YRS FLOAT(2),
	CAGE_YR INT,
	CAGE_MO FLOAT(1),
	SEX VARCHAR(1),
	RPT_DATE DATE,
	SYMPTOM_TEXT VARCHAR(255),
	DIED VARCHAR(1),
	DATEDIED DATE,
	L_THREAT VARCHAR(1),
	ER_VISIT VARCHAR(1),
	HOSPITAL VARCHAR(1),
	HOSPDAYS INT,
	X_STAY VARCHAR(1),
	DISABLE VARCHAR(1),
	RECOVD VARCHAR(1),
	VAX_DATE DATE,
	ONSET_DATE DATE,
	NUMDAYS INT,
	LAB_DATA VARCHAR(255),
	V_ADMINBY VARCHAR(3),
	V_FUNDBY VARCHAR(3),
	OTHER_MEDS VARCHAR(255),
	CUR_ILL VARCHAR(255),
	HISTORY VARCHAR(255),
	PRIOR_VAX VARCHAR(128),
	SPLTTYPE VARCHAR(25),
	FORM_VERS INT,
	TODAYS_DATE DATE,
	BIRTH_DEFECT VARCHAR(1),
	OFC_VISIT VARCHAR(1),
	ER_ED_VISIT VARCHAR(1),
	ALLERGIES VARCHAR(255),
	PRIMARY KEY (VAERS_ID)
);

CREATE TABLE VAERS_VAX_Symptoms (
	VAERS_ID INT,
	VAX_TYPE VARCHAR(15),
	VAX_MANU VARCHAR(40),
	VAX_NAME VARCHAR(100),
	SYMPTOM1 VARCHAR(100),
	SYMPTOM2 VARCHAR(100),
	SYMPTOM3 VARCHAR(100),
	SYMPTOM4 VARCHAR(100),
	SYMPTOM5 VARCHAR(100),
	PRIMARY KEY (VAERS_ID)
);

SELECT * FROM VAERS_VAX_Symptoms;


SELECT *
  FROM [VAERS_VAX_Symptoms] 
  FULL JOIN VAERSData ON [VAERS_VAX_Symptoms].VAERS_ID = VAERSData.VAERS_ID
