CREATE TABLE VAERSData (
	VAERS_ID VARCHAR(6),
	RECVDATE DATE,
	STATE VARCHAR(2),
	AGE_YRS FLOAT(2),
	SEX VARCHAR(1),
	SYMPTOM_TEXT VARCHAR(255),
	DIED VARCHAR(1),
	DATEDIED DATE,
	L_THREAT VARCHAR(1),
	ER_VISIT VARCHAR(1),
	HOSPITAL VARCHAR(1),
	HOSPDAYS INT,
	X_STAY VARCHAR(1),
	DISABLE VARCHAR(1),
	RECOVD VARCHAR(1),
	VAX_DATE DATE,
	HISTORY VARCHAR(255),
	BIRTH_DEFECT VARCHAR(1),
	PRIMARY KEY (VAERS_ID)
);

CREATE TABLE VAERS_VAX_Symptoms (
	VAERS_ID INT,
	VAX_TYPE VARCHAR(15),
	VAX_MANU VARCHAR(40),
	VAX_NAME VARCHAR(100),
	SYMPTOM1 VARCHAR(100),
	SYMPTOM2 VARCHAR(100),
	SYMPTOM3 VARCHAR(100),
	SYMPTOM4 VARCHAR(100),
	SYMPTOM5 VARCHAR(100),
	PRIMARY KEY (VAERS_ID)
);

SELECT * FROM VAERS_VAX_Symptoms;


SELECT *
  FROM [VAERS_VAX_Symptoms] 
  FULL JOIN VAERSData ON [VAERS_VAX_Symptoms].VAERS_ID = VAERSData.VAERS_ID
