-- Using clean_Vaers_data.csv to import into below table after created.

CREATE TABLE VAERSData (
	VAERS_ID INT,
	RECVDATE DATE,
	STATE VARCHAR(2),
	AGE_YRS FLOAT(2),
	SEX VARCHAR(1),
	DIED VARCHAR(1),
	L_THREAT VARCHAR(1),
	ER_VISIT VARCHAR(1),
	HOSPITAL VARCHAR(1),
	HOSPDAYS INT,
	X_STAY VARCHAR(1),
	DISABLE VARCHAR(1),
	RECOVD VARCHAR(1),
	BIRTH_DEFECT VARCHAR(1),
	PRIMARY KEY (VAERS_ID)
);

DROP TABLE VAERSData;
DROP TABLE VAERS_VAX_Symptoms;

-- Using VAERS_Vax_Symptoms.csv to import into below table after created.

CREATE TABLE VAERS_VAX_Symptoms (
	VAERS_ID INT,
	VAX_TYPE VARCHAR(15),
	VAX_MANU VARCHAR(40),
	VAX_NAME VARCHAR(100),
	SYMPTOM1 VARCHAR(1000),
	SYMPTOM2 VARCHAR(1000),
	SYMPTOM3 VARCHAR(1000),
	SYMPTOM4 VARCHAR(1000),
	SYMPTOM5 VARCHAR(1000),
	PRIMARY KEY (VAERS_ID)
);

SELECT * FROM VAERS_VAX_Symptoms
LIMIT 10;

SELECT  RECVDATE, STATE, AGE_YRS, SEX, DIED, L_THREAT, ER_VISIT, HOSPITAL, HOSPDAYS, X_STAY, DISABLE, RECOVD, BIRTH_DEFECT, VAX_TYPE, VAX_MANU, VAX_NAME, SYMPTOM1, SYMPTOM2, SYMPTOM3, SYMPTOM4, SYMPTOM5
   FROM VAERSData 
   FULL JOIN VAERS_VAX_Symptoms
   ON VAERSData.VAERS_ID = VAERS_VAX_Symptoms.VAERS_ID;

